version: "2.0"
services:
    node:
      build: .
      ports:
        - "5000:5000"
      restart: always
      depends_on:
        - redis
      links: 
        - redis

    redis:
      image: redis:latest
      ports:
        - "6379:6379"
      restart: always
